---
- name: Add current user to video group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: video
    append: true
- name: Add current user to input group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: input
    append: true
- name: Install Sway
  become: true
  ansible.builtin.apt:
    name:
      - weston
      - sway
      - foot
      - wofi
      - xwayland
      - seatd
    state: present
- name: Enable seatd
  ansible.builtin.systemd_service:
    name: seatd.service
    enabled: true
- name: Start seatd
  ansible.builtin.systemd_service:
    name: seatd.service
    state: started

- name: Install Google Chrome
  ansible.builtin.include_tasks: package.yml
  vars:
    repo_name: google-chrome
    repo_key_url: https://dl.google.com/linux/linux_signing_key.pub
    repo_key_name: google.asc
    repo_arch: amd64,arm64
    repo_url: https://dl.google.com/linux/chrome/deb
    repo_distribution: stable
    repo_component: main
    packages:
      - google-chrome-stable
- name: Reload systemd user daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
- name: Enable Sway
  ansible.builtin.systemd_service:
    name: sway.service
    enabled: true
    scope: user
- name: Start Sway
  ansible.builtin.systemd_service:
    name: sway.service
    state: started
    scope: user
