---
- name: Configure AVF User
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - video
      - input
    append: true
    shell: /usr/bin/zsh
    
- name: Install AVF Packages
  become: true
  ansible.builtin.apt:
    name:
      - foot
      - wofi
    state: present

- name: Install Google Chrome
  ansible.builtin.include_tasks: package.yml
  vars:
    repo_name: google-chrome
    repo_key_url: https://dl.google.com/linux/linux_signing_key.pub
    repo_key_name: google.asc
    repo_arch: amd64,arm64
    repo_url: https://dl.google.com/linux/chrome/deb
    repo_distribution: stable
    repo_component: main
    packages:
      - google-chrome-stable