image: docker:stable

services:
    - docker:dind

stages:
    - build
    - release

variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
    DOCKER_DRIVER: overlay2

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
    stage: build
    script:
        - docker pull archlinux/base:latest || true
        - docker pull $CONTAINER_IMAGE:latest || true
        - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF -f .config/Dockerfile .
        - docker push $CONTAINER_IMAGE:$CI_BUILD_REF

release:
    stage: release
    script:
        - docker pull $CONTAINER_IMAGE:$CI_BUILD_REF
        - docker tag $CONTAINER_IMAGE:$CI_BUILD_REF $CONTAINER_IMAGE:latest
        - docker push $CONTAINER_IMAGE:latest
    only:
        - master
