#!/usr/bin/env bash
set -euo pipefail

ansible-playbook ~/.config/ansible/site.yml

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
