#!/usr/bin/env bash
set -euo pipefail

if [ -f ~/.config/ansible/site.yml ]; then
  ansible-playbook ~/.config/ansible/site.yml
fi

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
