[main]
font=sans:size=14
prompt="Apps: "
icon-theme=hicolor
icons-enabled=yes
fields=name,generic,exec
terminal=foot

# Floating geometry boundaries
width=25
lines=5
inner-pad=8

[colors]
background=141414ef
text=fffffffff
match=ff0055ff
selection=252525ff
selection-text=fffffffff
border=ffffff15

[border]
width=1
radius=10
