#!/bin/bash
#Fuck it you would have to kill me to get my yubikey anyway
USER_PIN=811991


function tolower()
{
	echo $1 | tr '[A-Z]' '[a-z]'
}

function reply_ok()
{
	echo "OK $*"
}

function reply_d()
{
	echo "D $*"
	echo "OK"
}

function error()
{
	echo "ERR 83886355 unknown command"
}

function main()
{
	echo "OK Your orders please"
	while read reply; do
			reply=$(tolower "$reply")
			case $reply in
				"getpin")
					reply_d $USER_PIN
				;;
				"bye")
					reply_ok "closing connection"
					break
				;;
				"getinfo pid")
					reply_d $BASHPID
				;;
				*)
				# This generally includes OPTION, SETDESC, SETPROMPT
				# i.e. things we don't care for if we're not displaying
				# a prompt
					reply_ok
				;;
			esac
	done
}

main

exit 0
