[libinput]
enable_tap=true
accel-speed=0.5

[core]
idle-time=0

[shell]
panel-position=bottom
locking=false
animation=none

[keyboard]
keymap_layout=us

# -------------------------------------------------------------
# STANDALONE START MENU BUTTON
# -------------------------------------------------------------
[launcher]
icon=/usr/share/icons/hicolor/scalable/apps/debian-logo.svg
path=/usr/bin/fuzzel