name: Build
on:
  schedule:
    - cron: '0 3 * * 0' #run 3am on Sunday
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Get Build Time and Date
        run: |
          echo "BUILD_DATE=$(date +%m-%d-%Y)" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date +%H:%M)" >> $GITHUB_ENV
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .config/Dockerfile
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_TIME=${{ env.BUILD_TIME }}
            GITHOST=github.com
          platforms: linux/amd64
          push: true
          tags: jckimble/dotfiles:latest
